<?xml version="1.0"?>
<record>
  <result xmlns:dri="http://www.driver-repository.eu/namespace/dri" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">
    <header>
      <dri:objIdentifier>$id$</dri:objIdentifier>
      <dri:dateOfCollection>$dateofcollection$</dri:dateOfCollection>
      <dri:dateOfTransformation>$dateoftransformation$</dri:dateOfTransformation>
    </header>
    <metadata>
      <oaf:entity xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
		    xmlns:oaf="http://namespace.openaire.eu/oaf"
		    xsi:schemaLocation="http://namespace.openaire.eu/oaf $schemaLocation$">
		$it$
      </oaf:entity>
    </metadata>
  </result>
</record>